### ISSUE TITLE
Using NuPIC Visualizer + header update

### ISSUE THREAD

**Issue by breznak** [breznak/ML.benchmark#7]
- we could mention https://github.com/nupic-community/nupic.visualizations in the readme and use it for generating the images for results
  - this would require a modification to the `header files`: the Visualizer expects `timestamp` (check the spelling in their readme, if there's time_stamp or what..) but we've got `time`. Don't do this by hand, we should write a shell script to replace the word in CSV files and the generating .m files. 
  - a minor spelling issue is `fazeSomething` should probably be `phaseSomething` (do this with the same script)

CC @wattik

**Comment by breznak** [comment]
@wattik with the header update suitable for the nupic.visualizer, what's your experience using it as an alternative to the matlab plot? 
If it works, we should just add a link to the readme and can close this issue. If not, we can file bugs for it.

**Comment by breznak** [comment]
- [ ] The `time_stamp` in the generating scripts still needs change to `timestamp`, 
- [ ] then regenerate data (we can keep results, as only change is in the name of a column) and push

**Comment by breznak** [comment]
I can then test and close this.

**Comment by breznak** [comment]
@wattik I'm working on this right now (if you haven't done the work alr.), the datasets need to be regenerated with the changed scripts. At least I'll try it here.

**Comment by breznak** [comment]
@wattik I still have trouble replicating all the datasets easily. in the `main.m`, you can see the files still unchanged by this command `grep -R 'time_stamp' .` 
Can you please add the parts (don't worry, no harm in duplicating the code a bit, don't make it too complex) to main so all files are generated? Or review if we have some old left-over files.

**Comment by wattik** [comment]
Most of them are old. I suggest we'll delete all of them and create new ones.
